name: GBNP
version: 1.0dev
date: 2016-03-08
description: |
    computing Gröbner bases of noncommutative polynomials

authors:
    - name: A.M. Cohen
      url: http://www.win.tue.nl/~amc
    - name: J.W. Knopper
      url: mailto:J.W.Knopper@tue.nl

maintainers:
    - name: A.M. Cohen
      url: http://www.win.tue.nl/~amc
    - name: J.W. Knopper
      url: mailto:J.W.Knopper@tue.nl
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/gbnp/
readme: README.md
packageinfo: https://gap-packages.github.io/gbnp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/gbnp/releases/download/v1.0dev/gbnp-1.0dev.tar.gz

abstract: |
    The <span class="pkgname">GBNP</span> package provides algorithms for    computing Grobner bases of noncommutative polynomials with coefficients    from a field implemented in <span class="pkgname">GAP</span> and with    respect to the "total degree first then lexicographical" ordering.    Further provided are some variations, such as a weighted and truncated    version and a tracing facility. The word "algorithm" is to be    interpreted loosely here: in general one cannot expect such an algorithm    to terminate, as it would imply solvability of the word problem for    finitely presented (semi)groups.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Grobner basis, noncommutative polynomial, partial Hilbert series.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>CKT16</span>]   <b class='BibAuthor'>Cohen, A., Knopper, J. and GAP Team, T.</b>,
     <i class='BibTitle'>GBNP, computing Gröbner bases of noncommutative polynomials,
             Version 1.0dev</i>
     (<span class='BibYear'>2016</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/gbnp/">https://gap-packages.github.io/gbnp/</a></span>.
    </p>
    

bibtex: |
    @misc{ GBNP1.0dev,
      author =           {Cohen, A. and Knopper, J. and GAP Team, T.},
      title =            {{GBNP}, computing Gr{\"o}bner bases of noncommutative polynomials, {V}ersion 1.0dev},
      month =            {Mar},
      year =             {2016},
      note =             {Refereed GAP package},
      howpublished =     {\href {https://gap-packages.github.io/gbnp/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{gbnp/}}},
      keywords =         {Grobner basis; noncommutative polynomial; partial Hilbert series},
      printedkey =       {CKT16}
    }

